// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAxsK4nYkTIoy09ZCSnV8rTdzzNpDfFGs',
    appId: '1:247065335725:web:fd7a207fc875b0c406f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    authDomain: 'reporting-mad-app.firebaseapp.com',
    storageBucket: 'reporting-mad-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvksoUF_O3oQ1BC7wnEjBfrrslqyNqSm0',
    appId: '1:247065335725:android:dfd37253d3815e6006f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    storageBucket: 'reporting-mad-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOq7C5Q4jFmsSo0Pe6W2ngjUXepCMUP9s',
    appId: '1:247065335725:ios:1c6b321d2325429406f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    storageBucket: 'reporting-mad-app.appspot.com',
    iosClientId: '247065335725-kteb2g58395hi3s9i4u4rmject5p0f8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOq7C5Q4jFmsSo0Pe6W2ngjUXepCMUP9s',
    appId: '1:247065335725:ios:64859b85f9a5c21006f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    storageBucket: 'reporting-mad-app.appspot.com',
    iosClientId: '247065335725-5td01gd6vl7p6vrov63031fjss3q862h.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintain.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAxsK4nYkTIoy09ZCSnV8rTdzzNpDfFGs',
    appId: '1:247065335725:web:c989281a7776490706f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    authDomain: 'reporting-mad-app.firebaseapp.com',
    storageBucket: 'reporting-mad-app.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAAxsK4nYkTIoy09ZCSnV8rTdzzNpDfFGs',
    appId: '1:247065335725:web:fcc1d20caf758cdc06f324',
    messagingSenderId: '247065335725',
    projectId: 'reporting-mad-app',
    authDomain: 'reporting-mad-app.firebaseapp.com',
    storageBucket: 'reporting-mad-app.appspot.com',
  );
}
